avatar: https://s1.imagehub.cc/images/2023/12/11/5a8c04cc26f5874836c77986343605ab.gif # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
    path: https://cdn.luogu.com.cn/upload/image_hosting/imbnzgmv.png
    width: 1280
    height: 720
favicon:
    href: https://cdn.luogu.com.cn/upload/usericon/389924.png # 网站图标
    type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

# 附加图标库 使用说明：https://hexo.kira.host/config/icon.html
# iconlib: //at.alicdn.com/t/font_3299330_el19bsi97h8.css


cdn: # 这里可以修改站点使用的库的CDN
    gitalk:
        css: https://unpkg.com/gitalk@latest/dist/gitalk.css
        js: https://unpkg.com/gitalk@latest/dist/gitalk.min.js
    giscus:
        js: https://giscus.app/client.js

#beian: 萌ICP备20239730号 # 备案号（选填，此乃中国特色，不得不尝）

menu:
    回到首页:
        - /
        - icon-home
    文章归档: # 使用说明：https://docs.kira.com/article/archive
        - /archive.html
        - icon-container
    关于本人:
        - /aboutme.html
        - icon-user
    我的友链:
        - /favorite.html # 使用说明：https://docs.kira.com/article/py
        - icon-menu 

widgets:
    - social
    - tagcloud
    - category

maxTagcloud: 0 # 标签云组件显示的标签数量，0 表示不限制

social:
    QQ:
        - tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=3221369254&website=www.oicqzone.com
        - icon-QQ
        - rgb(49, 174, 255)
        - rgba(49, 174, 255, .1)
    哔哩哔哩:
        - https://space.bilibili.com/1456751766
        - icon-bilibili
        - rgb(231, 106, 141)
        - rgba(231, 106, 141, .15)
    GitHub:
        - https://github.com/adolphshi/
        - icon-github
        - rgb(25, 23, 23)
        - rgba(25, 23, 23, .15)
#    Gitee:
#        - https://gitee.com/ch1ny/
#        - icon-gitee
#        - rgb(165, 15, 15)
#        - rgba(165, 15, 15, .15)

color: # 配色方案，从first到seventh为优先级为1-7的颜色，默认为彩虹配色
    first: # 同时作为主题色
        r: 49
        g: 174
        b: 255
    second:
        r: 255
        g: 78
        b: 106
    third:
        r: 255
        g: 185
        b: 0
    fourth:
        r: 51
        g: 213
        b: 122
    fifth:
        r: 0
        g: 219
        b: 255
    sixth:
        r: 255
        g: 69
        b: 0
    seventh:
        r: 144
        g: 144
        b: 255

# 评论区
gitalk:
    active: false # 是否启用 gitalk
    admin: -your github username- # 拥有对该repo进行操作的 GitHub username
    owner: -your github username- # 持有该 repo 的 GitHub username
    repo: -issue repo name- # 存放评论的 issue 所在的 repo
    clientID: -id- # GitHub Client ID
    clientSecret: -key- # GitHub Client Secret
    title: '' # Gitalk Issue Title
giscus:
    active: true # 是否启用 giscus
    repo: adolphshi/adolph # 存放评论的 discus 所在的 repo
    repoID: R_kgDOLDiSmQ # GitHub repo ID
    category: Announcements
    categoryID: DIC_kwDOLDiSmc4CcWTz
    mapping: pathname # pathname, url, title, og:title, specific, number
    # term: # abc 123 # specific | number
    theme: dark
    lang: zh-CN

copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'
copyTip: "著作权归作者所有。\n商业转载请联系作者获得授权，非商业转载请注明出处。\n来源：%url" # 自定义复制版权文案,使用 %url 代替当前页面URL, 修改为false禁用

# 自定义侧边栏尾部内容
sidebar: '<a href="https://icp.gov.moe/?keyword=20235011" target="_blank">萌ICP备20235011号</a>'

# 友链配置
favorites:
    - avatar: https://travel.moe/images/icon/icon64.png
      link: https://travel.moe/go.html
      name: 异次元之旅
friends:
    - avatar: https://cdn.luogu.com.cn/upload/image_hosting/m6h9xlus.png
      link: https://dolphin613.github.io/
      name: dolphin613
    - avatar: https://s1.imagehub.cc/images/2024/05/28/acf81467bf595170a200a61cf3d9c0c2.png
      link: https://minecraftdream12345.github.io/
      name: zMr
# 自定义样式，使用前请阅读 https://hexo.kira.host/config/customStyles.html
customStyles:
    - style
    - custom

# 可复制的代码块
copyableCodeblock: true

math:
  enable: true
  per_page: true
  #engine: mathjax
  engine: katex
 
  katex:
    # Use 0.7.1 as default, jsdelivr as default CDN, works everywhere even in China
    cdn: //cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css
    #cdn: //cdn.jsdelivr.net/npm/katex@0.7.1/dist/katex.min.css
    # CDNJS, provided by cloudflare, maybe the best CDN, but not works in China
    #cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
 
    copy_tex:
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      enable: true
      copy_tex_js: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.js
      copy_tex_css: //cdn.jsdelivr.net/npm/katex@0/dist/contrib/copy-tex.min.css